import React from 'react';
import { LuPlane } from "react-icons/lu";


const YourTravial = () => {
    return (
        <div className='bg-primary text-white flex  items-center justify-between'>
            <div className='md:py-20 py-10 md:px-48 px-5 md:max-w-[60%]'>
                <h2 className='flex items-center gap-2 md:text-5xl text-3xl font-semibold'><LuPlane /> Are you a traveler?</h2>
                <div>
                    <p className='my-5 leading-[1.8]'>Emma has a direct flight from Paris to New York, an approximately 8-hour journey. In her suitcase, 10 kg of unused space.</p>
                    <p className='my-5 leading-[1.8]'>On the other side, Alex is desperately trying to send a 5 kg package of gifts to his sister living in New York. Rather than paying for an expensive and slow international shipping service, he finds Emma on CoBag.</p>
                    <p className='my-5 leading-[1.8]'>Alex contacts Emma through the platform.They set up a meeting. Alex hands over the package to Emma, along with a security code generated by CoBag.</p>
                    <p className='my-5 leading-[1.8]'>Emma boards the flight, transports the package, and hands it over to Alex's sister in New York. Once the code is validated, Emma receives her payment.</p>
                </div>
                <div className='my-10'>
                    <h2 className='font-semibold'>💡 Fast, simple, secure.</h2>
                    <ul className='list-disc pl-8'>
                        <li className='my-2'>Emma earns money: she receives €7 per kg transported (minimum €12).</li>
                        <li className='my-2'>Alex benefits from express delivery: his package arrives at the same time as Emma's flight. </li>
                    </ul>
                </div>
                <h2><span className='font-semibold'>Are you traveling?</span> Your luggage becomes a valuable asset. Earn money simply by sharing your unused space.</h2>
                <button className='bg-gradient-to-r from-[#98DED9] to-[#C7FFD8] py-3 px-10 text-primary font-semibold rounded-md mt-10 '>Learn more</button>
            </div>
            <div className='md:block hidden'>
                <img className='max-w-[700px]' src="/Images/Ourconcept/image.png" alt="" />
            </div>
        </div>
    );
}

export default YourTravial;
