"use client";
import React from "react";
import { createRoot } from 'react-dom/client';
import i18n from "i18next";
import { useTranslation, initReactI18next } from "react-i18next";



i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    // the translations
    // (tip move them in a JSON file and import them,
    // or even better, manage them via a UI: https://react.i18next.com/guides/multiple-translation-files#manage-your-translations-with-a-management-gui)
    resources: {

      en: {
        translation: {
          'navWhatdoWYouWantTo': "What do you want to do?",
          'Discoverourservices': 'Discover our services',
          "NavbarItem1": "I want to sell my kilos",
          "NavbarItem2": "I want to send a parcel",
          "NavbarItem3": "I want to have my excess baggage transported",
          "NavbarItem4": "I want to buy abroad",
          'NavCommission': '0% Commission',
          'NavSubscribe': 'Subscribe',
          'NavProfile': 'Profile',
          'HeroSecureDelivery': 'Secure Delivery & Payment',
          'ShareYourLuggagesaveMoney': 'Share Your Luggage, save Money',
          'CoBagreimbursesyourLuggage': 'CoBag reimburses your Luggage',
          'Sellmyunusedkilos': 'Sell my unused kilos',
          'Searchforatraveler': ' Search for a traveler',
          'SiteYouKnow': 'You know',
          'SiteCARPOOLING': 'CARPOOLING',
          'SiteCOLOCATION': 'CO-LOCATION',
          'SiteCOWORKING': 'CO-WORKING',
          'SiteCObagSharing': 'As you will have understood, the principle of CoBag is simple:',
          'SiteCObagSharingwhat': 'Sharing what?',
          'CoBagreimbursesyourluggage': 'CoBag rembourse vos bagages',
          'Resellyour': 'Resell your',
          'unusedkilos': 'unused kilos',
          'inyoursuitcasesand': 'in your suitcases and',
          'earnmoney': 'earn money',
          'oneveryplaneortraintrip': 'on every plane or train trip',
          'WhodoIsellto': 'Who do I sell to?',
          'TootherCoBagusers': 'To other CoBag users who will take advantage of your trips for their shipments. Transform your unused kilos into cash and reimburse your suitcase',
          'Sellmyunusedkilos': 'Sell my unused kilos',
          'ResellyourunusedkilosCoBag': 'Resell your unused kilos at 7€/kg with CoBag',
          'YourluggageishighlysafewithCobag': 'Your luggage is highly safe with Cobag',
          'TravelwithpeaceofmindwithCobag': 'Travel with peace of mind : with Cobag is high-level security, you stay in control of your luggage and no unauthorized item can slip through.',
          'Takeeverythingwithyouwithout': 'Take everything with you without leaving your belongings at the door',
          'Whatifyourexcessluggage': 'What if your excess luggage had a place in other people is suitcases? Team up with another CoBag traveler',
          'Howdoesitworkit': 'How does it work?',
          'ThankstoCoBagbuythe': 'Thanks to CoBag, buy the unused kilos of a co-passenger of the same flight and share their suitcases to take all your luggage without leaving anything behind, at a reduced price.',
          'Asurplusin': 'A surplus in',
          'yourluggage2': 'your luggage?',
          'Useupunusedkilosinperson': 'Use up unused kilos in a person is luggage',
          'otherpassenger': 'other passenger',
          'Transportmysurplus': 'Transport my surplus',
          'StandtogetherwithCoBag': 'Stand together with CoBag',
          "AccessProducts12": "Access products from around the world, without borders",
          "Description121": "The whole world at your fingertips, thanks to our travel couriers",
          "HowDoesItWork12": "How does it work?",
          "HowItWorks121": "A CoBag courier traveler located in the desired country will purchase the product for you and bring it back in his suitcase upon his return to deliver it to you.",
          "ProductNotFound21": "A product",
          "ProductNotFoundDesc12": "not found?",
          "TravelerReports12": "A CoBag traveler",
          "ReportsIt12": "reports it to you",
          "FindMyBuyer12": "Find my buyer",
          "MakeInaccessiblePossible12": "Make the inaccessible possible with CoBag",
          "faster-delivery": "Faster delivery than express",
          "benefit": "Benefit from the ultra-speed of a direct flight for sending your parcels internationally",
          "how-does-it-work": "How does it work?",
          "how-it-works121": "Do you have an urgent package to send internationally? With CoBag, a traveler takes charge of your package in the available space of his luggage, takes it with him on his flight and delivers it upon arrival at his destination.",
          "sending-package": "Sending the package",
          "sending-time": "Paris 10:00 a.m.",
          "arrival-package": "Arrival of the package",
          "arrival-time": "Casablanca 1:00 p.m.",
          "find-carrier": "Find a carrier",
          "faster-cheaper": "100% faster, 75% cheaper with CoBag",
          "Howdoesitwork1001": "How does it work?",
          "Postorsearchforanad1002": "Post or search for an ad",
          "Publishyourtriporfindatravelerthatmeetsyourneeds1003": "Publish your trip or find a traveler that meets your needs.",
          "Chatviaourmessaging1004": "Chat via our messaging",
          "Validatealldetailsviaourintegratedsecuremessaging1005": "Validate all details via our integrated secure messaging.",
          "Confirmdelivery1006": "Confirm delivery",
          "Usethesecurecodetocompletethetransactionsecurely1007": "Use the secure code to complete the transaction securely.",
          "LearnMore1008": "Learn More",
          "WhoCanISellMyUnusedKilosTo1001": "Who can I sell my unused kilos to?",
          "DeliveryImageAltText1002": "Delivery",
          "FastestInternationalDelivery1003": "The fastest international delivery in the world",
          "SendParcelsWorldwide1004": "For those who want to send parcels worldwide with lightning delivery.",
          "SellUnusedKilosDescription1005": "By selling your unused kilos, users can ship their parcels as fast as the duration of your flight. Say goodbye to endless postal delays: with Cobag, you become the immediate solution for express and reliable deliveries across the globe.",
          "LearnMore1006": "Learn more",
          "DeliveryImageAltText1007": "Delivery",
          "UniqueRevolutionaryWorldwide1008": "Unique and revolutionary worldwide",
          "PurchaseRareProductsAbroad1009": "For those who wish to purchase rare products abroad",
          "UnobtainableProductsDescription1010": "Unobtainable products, limited editions, local exclusives: your journeys become their direct access. You buy for them the products they cannot get at home. With Cobag, you make the inaccessible possible.",
          "LearnMore1011": "Learn more",
          'Examplesofshipments': 'Examples of shipments',
          'Documents5454': 'Documents',
          'Urgentadministrativedocuments': 'Urgent administrative documents.',
          'Clothessdf4554': 'Clothes',
          'Surpriseyourlovedonesquickly': 'Surprise your loved ones quickly.',
          'Food54445': 'Food',
          'Traditionalfoodproducts': 'Traditional food products.',
          'Medicine456sdf': 'Medicine',
          'Expressdeliveryofurgentmedications': 'Express delivery of urgent medications.',
          'Pleasecheckthelist': '*Please check the list of products allowed by your transport company.',
          'Examplesofpurchases': 'Examples of purchases',
          'Koreanskincare': 'Korean skincare',
          'AuthenticKoreanBeauty': 'Authentic Korean Beauty and Skincare Products.',
          'Clothes4545': 'Clothes',
          'Internationalfashion': 'International fashion and trends.',
          'Limitededitionsneakers': 'Limited edition sneakers.',
          'Exclusivemodelsandrarecollections.': 'Exclusive models and rare collections.',
          'Allproductsaresubjecttocurrentcustomsregulations': '* * All products are subject to current customs regulations',
          'Identityverified': 'Identity verified',
          'Allusersareverifiedincluding': 'All users are verified, including senders, buyers and travelers, with ticket validation to ensure a reliable and secure service.',
          'Securepayment3554': 'Secure payment',
          'Paymentsarehelduntildeliverytransparent': 'Payments are held until delivery is confirmed, ensuring a safe and transparent transaction',
          'Securitycode2541': 'Security code',
          'Two5445zdf41': 'Two',
          '4digitcodes': '4-digit codes',
          'secureeachstepuponhandover': 'secure each step: upon handover and delivery, guaranteeing maximum traceability and security.',
          'CoBagInsurance345': 'CoBag Insurance',
          'BenefitfromcomprehensivecoveragewithCoBag': 'Benefit from comprehensive coverage with CoBag',
          'insurance5sd54ff': "insurance",
          'protectingyourparcelsupto': ', protecting your parcels up to',
          'prices€1000': '€1000',
          'incaseincidentpeacemindyourshipments': 'in case of any incident. Travel with peace of mind, your shipments are secure',
          "CoBagTravelshareconnect": "CoBag: Travel, share, connect.",
          "Whatifyoursuitcaseisvaluable": "What if your suitcase is more valuable than you thought?",
          "Turnyourunusedluggagespace": "Turn your unused luggage space into a profitable opportunity. With CoBag, every trip becomes a chance",
          "Earnmoneywhilehelpingothers": "to earn money while helping others.",
          "heading1212121": "CoBag: Turn Extra Space Into Opportunities!",
          "paragraph1121212": "CoBag is a revolutionary platform that connects travelers, senders, and buyers to maximize the use of unused baggage space. Whether you're traveling light, dealing with excess baggage, or need to transport something internationally, CoBag has you covered.",
          "heading2456": "How It Works?",
          "step1_title": "For Travelers Selling Unused Kilos:",
          "step1_description": "Got extra kilos in your luggage? List your trip on CoBag and offer your unused baggage space to people who need it. Transport excess baggage, parcels, or even international purchases. Earn money effortlessly and securely while you travel.",
          "step2_title": "For Those With Excess Baggage:",
          "step2_description": "Avoid costly airline fees by renting unused kilos from travelers already taking the same flight or train. Hand over your extra luggage securely and save money.",
          "step3_title": "For International Buyers:",
          "step3_description": "Looking for a product that’s unavailable in your country? Connect with a traveler in the region who can purchase it for you and bring it back. Pay securely through the platform, and receive your item upon the traveler’s return.",
          "step4_title": "For Parcel Senders:",
          "step4_description": "Need to send a parcel quickly? CoBag connects you with a traveler heading to your desired destination. Arrange for delivery, either in person or via a secure locker at the airport.",
          "WhyChooseCoBag45": "Why Choose CoBag?",
          "Secure456": "User identities, trips, and parcel contents are verified. Payments are held until the mission is completed successfully.",
          "EcoFriendly546": "CoBag uses space on flights and trains that are already traveling, reducing unnecessary CO2 emissions.",
          "Affordable456456": "Save on expensive excess baggage fees and international shipping costs.",
          "Flexible4566": "Choose the service that suits your needs—whether you’re selling kilos, sending parcels, or making purchases abroad.",
          "JoinTheCoBagMovement54645": "Join the CoBag Movement Today!",
          'Whetheryoure4241': ' Whether you’re a traveler, a sender, or a buyer, CoBag helps you make the most of every trip. Turn unused baggage space into opportunities and experience a smarter, greener way to travel.',
          "SignUpNow456": "Sign Up Now",
          'logoitem101': 'Co',
          'logoitem102': 'B',
          'logoitem103': 'ag  When Your',
          'Luggage542121': "Luggage",
          'TravelsforYouandforOthers': 'Travels for You... and for Others.',
          'CoBagwasborn455': 'CoBag was born from a moment of inspiration during a trip that revealed the hidden potential of unused luggage space. What started as a simple frustration became a revolutionary way to connect people across the globe.',
          "birthOfIdeaTitle2": "The birth of an idea",
          "birthOfIdeaDescription2": "The founder of CoBag got the idea for his startup while traveling. On the way there, he had luggage full to bursting, between souvenirs and gifts, and couldn't take everything. But on the way back, his suitcases were empty... and yet, he had already paid for all that unused, wasted space.",
          "revolutionaryTitle": "Revolutionary",
          "revolutionaryDescription": "That's when the idea came to him: Why not share this unused space with other people? A simple but effective solution to use the free space of luggage intelligently, reducing the number of planes and trucks on the road, and therefore the carbon footprint. An innovative, ecological and extremely fast solution: in just a few hours, the time of a direct flight, a package crosses the world for delivery even more express than express.",
          "notOnlyThatTitle": "But that's not all",
          "notOnlyThatDescription": "But that's not all: during the trip, the founder also noticed another need. Not everyone has relatives or friends traveling internationally to bring back rare or exclusive products. With CoBag, travelers can now buy and bring back products from all over the world for those who need them.",
          "joinTheRevolutionTitle": "Join the CoBag revolution today and travel smart with your luggage!",
          "commissionMessage21": "Enjoy 0% commission on all your missions with",
          "monthlyFeeMessage": "For only €10 per month, without commitment, optimize your earnings and reduce your costs on each transaction.",
          'Subscribenow1': 'Subscribe now',
          "TheCoBagSkyAdvantages": "The CoBag Sky advantages",
          "PremiumExperience": "A premium experience to optimize your missions",
          "ZeroCommissions": "0% commissions",
          "ZeroCommissionFee": "0% commission fee. An ideal solution to maximize your earnings",
          "InsurancePlusIncluded": "Insurance Plus included",
          "EnjoyCompleteFlexibility": "Enjoy complete flexibility with the ability to cancel at any time. Stay in control of your subscription",
          "NoCommitment": "Sans engagement",
          "StayInControl": "Enjoy complete flexibility with the ability to cancel at any time. Stay in control of your subscription",
          "OneSubscriptionUniqueBenefits": "One subscription, unique benefits",
          "PricePerMonth": "10€",
          "ZeroCommission": "0% commission on all transactions",
          "NoCommitment2": "No commitment: total freedom",
          "ImmediateSavings": "Immediate savings for buyers and sellers",
          "InsurancePlusIncluded": "Plus Insurance included up to €500",
          "CoBagSkyBadge": "CoBag Sky badge on your profile",
          "PricePerMonthSaved": "month saved by our members",
          "SavingsByMembers": "Members save an average of €30 per month with CoBag Sky*",
          "AverageSavingsExplanation": "*Average savings made per month, calculated on the basis of all missions carried out over a month, thanks to the €0 commission fees",
          "BecomeAMember": "Become a member for only €10 per month",
          "BenefitsUsableAnywhere": "Your benefits are usable wherever CoBag Sky is present",
          "OfferYourJourney": "Offer your journey, Make your luggage profitable.",
          "ResellUnusedKilos": "Resell your unused kilos and turn your trips intolucrative opportunities.",
          "Plane": "Plane",
          "Train": "Train",
          
          "TransportMood": "Transport Mood",
          "Direct": "Direct",
          "WithCorrespondence": "Transport Mood",
          "AddYourTicket": "(PNG, JPG or PDF up to 10MB)",
          "FlightNumber": "Flight Number",
          "DepartureCity": "Departure City",
          "ArrivalCity": "Arrival city",
          "DepartureDate": "Departure Date",
          "ArrivalDate": "Arrival Date",
          "DepartureTime": "Departure time",
          "ArrivalTime": "Departure time",
          "AvailableWeight": "Available weight",

          "HandLuggage": "Hand luggage",
          "CheckedBaggage": "Checked baggage",
          
          "AvailableToBeACourier": "Available to be a courier",
          "MaximumPurchaseAmountYouAreWillingToAdvance": "Maximum purchase amount you are willing to advance.",
          "EnterTheAmount": "Enter the amount",
          "ThisAmountWillBeVisibleToPotentialBuyers": "This amount will be visible to potential buyers.",
          "MessageOptional": "Message (optional)",
          "PublishRoute": "Publish the Route",





        }
      },

      fn: {
        translation: {
          "navWhatdoWYouWantTo": "Que voulez-vous faire ?",
          "Discoverourservices": "Découvrez nos services",
          "NavbarItem1": "Je veux vendre mes kilos",
          "NavbarItem2": "Je veux envoyer un colis",
          "NavbarItem3": "Je veux faire transporter mon excédent de bagages",
          "NavbarItem4": "Je veux acheter à l'étranger",
          "NavCommission": "0% de commission",
          "NavSubscribe": "Abonnez-vous",
          "NavProfile": "Profil",
          "HeroSecureDelivery": "Livraison et Paiement Sécurisés",
          "ShareYourLuggagesaveMoney": "Partagez vos bagages, économisez de l'argent",
          "CoBagreimbursesyourLuggage": "CoBag rembourse vos bagages",
          "Sellmyunusedkilos": "Vendez mes kilos inutilisés",
          "Searchforatraveler": "Recherchez un voyageur",
          "SiteYouKnow": "Vous savez",
          "SiteCARPOOLING": "COVOITURAGE",
          "SiteCOLOCATION": "CO-LOCATION",
          "SiteCOWORKING": "CO-WORKING",
          "SiteCObagSharing": "Comme vous l'aurez compris, le principe de CoBag est simple :",
          "SiteCObagSharingwhat": "Partager quoi ?",
          "CoBagreimbursesyourluggage": "CoBag rembourse vos bagages",
          "Resellyour": "Revendez vos",
          "unusedkilos": "kilos inutilisés",
          "inyoursuitcasesand": "dans vos valises et",
          "earnmoney": "gagnez de l'argent",
          "oneveryplaneortraintrip": "à chaque voyage en avion ou en train",
          "WhodoIsellto": "À qui est-ce que je vends ?",
          "TootherCoBagusers": "À d'autres utilisateurs de CoBag qui profiteront de vos voyages pour leurs envois. Transformez vos kilos inutilisés en argent et remboursez votre valise",
          "Sellmyunusedkilos": "Vendre mes kilos inutilisés",
          "ResellyourunusedkilosCoBag": "Revendez vos kilos inutilisés à 7€/kg avec CoBag",
          "YourluggageishighlysafewithCobag": "Vos bagages sont hautement sécurisés avec CoBag",
          "TravelwithpeaceofmindwithCobag": "Voyagez l'esprit tranquille : avec CoBag, la sécurité est de haut niveau, vous gardez le contrôle de vos bagages et aucun objet non autorisé ne peut passer.",
          "Takeeverythingwithyouwithout": "Emportez tout avec vous sans laisser vos affaires à la porte",
          "Whatifyourexcessluggage": "Et si votre excédent de bagages avait une place dans les valises des autres ? Faites équipe avec un autre voyageur CoBag",
          "Howdoesitworkit": "Comment ça marche ?",
          "ThankstoCoBagbuythe": "Grâce à CoBag, achetez les kilos inutilisés d'un co-passager du même vol et partagez leurs valises pour emporter tous vos bagages sans rien laisser derrière, à prix réduit.",
          "Asurplusin": "Un excédent dans",
          "yourluggage2": "vos bagages ?",
          "Useupunusedkilosinperson": "Utilisez des kilos inutilisés dans les bagages d'une autre personne",
          "otherpassenger": "autre passager",
          "Transportmysurplus": "Transportez mon excédent",
          "StandtogetherwithCoBag": "Soyons ensemble avec CoBag",
          "AccessProducts12": "Accédez aux produits du monde entier, sans frontières",
          "Description121": "Le monde entier à portée de main, grâce à nos coursiers de voyage",
          "HowDoesItWork12": "Comment ça marche ?",
          "HowItWorks121": "Un voyageur CoBag situé dans le pays souhaité achètera le produit pour vous et le ramènera dans sa valise à son retour pour vous le livrer.",
          "ProductNotFound21": "Un produit",
          "ProductNotFoundDesc12": "pas trouvé ?",
          "TravelerReports12": "Un voyageur CoBag",
          "ReportsIt12": "vous le signale",
          "FindMyBuyer12": "Trouver mon acheteur",
          "MakeInaccessiblePossible12": "Rendre l'inaccessible possible avec CoBag",
          "faster-delivery": "Livraison plus rapide que l'express",
          "benefit": "Bénéficiez de la vitesse ultra d'un vol direct pour envoyer vos colis à l'international",
          "how-does-it-work": "Comment ça marche ?",
          "how-it-works121": "Vous avez un colis urgent à envoyer à l'international ? Avec CoBag, un voyageur prend en charge votre colis dans l'espace disponible de ses bagages, l'emporte avec lui lors de son vol et vous le livre à son arrivée à destination.",
          "sending-package": "Envoi du colis",
          "sending-time": "Paris 10h00",
          "arrival-package": "Arrivée du colis",
          "arrival-time": "Casablanca 13h00",
          "find-carrier": "Trouver un transporteur",
          "faster-cheaper": "100% plus rapide, 75% moins cher avec CoBag",
          "Howdoesitwork1001": "Comment ça marche ?",
          "Postorsearchforanad1002": "Publiez ou recherchez une annonce",
          "Publishyourtriporfindatravelerthatmeetsyourneeds1003": "Publiez votre voyage ou trouvez un voyageur répondant à vos besoins.",
          "Chatviaourmessaging1004": "Discutez via notre messagerie",
          "Validatealldetailsviaourintegratedsecuremessaging1005": "Validez tous les détails via notre messagerie sécurisée intégrée.",
          "Confirmdelivery1006": "Confirmez la livraison",
          "Usethesecurecodetocompletethetransactionsecurely1007": "Utilisez le code sécurisé pour finaliser la transaction en toute sécurité.",
          "LearnMore1008": "En savoir plus",
          "WhoCanISellMyUnusedKilosTo1001": "À qui puis-je vendre mes kilos inutilisés ?",
          "DeliveryImageAltText1002": "Livraison",
          "FastestInternationalDelivery1003": "La livraison internationale la plus rapide au monde",
          "SendParcelsWorldwide1004": "Pour ceux qui souhaitent envoyer des colis dans le monde entier avec une livraison éclair.",
          "SellUnusedKilosDescription1005": "En vendant vos kilos inutilisés, les utilisateurs peuvent expédier leurs colis aussi rapidement que la durée de votre vol. Dites adieu aux retards postaux interminables : avec Cobag, vous devenez la solution immédiate pour des livraisons express et fiables à travers le monde.",
          "LearnMore1006": "En savoir plus",
          "DeliveryImageAltText1007": "Livraison",
          "UniqueRevolutionaryWorldwide1008": "Unique et révolutionnaire dans le monde entier",
          "PurchaseRareProductsAbroad1009": "Pour ceux qui souhaitent acheter des produits rares à l'étranger",
          "UnobtainableProductsDescription1010": "Produits introuvables, éditions limitées, exclusivités locales : vos voyages deviennent leur accès direct. Vous achetez pour eux les produits qu'ils ne peuvent pas obtenir chez eux. Avec Cobag, vous rendez l'inaccessible possible.",
          "LearnMore1011": "En savoir plus",
          "Examplesofshipments": "Exemples d'expéditions",
          "Documents5454": "Documents",
          "Urgentadministrativedocuments": "Documents administratifs urgents.",
          "Clothessdf4554": "Vêtements",
          "Surpriseyourlovedonesquickly": "Surprenez vos proches rapidement.",
          "Food54445": "Nourriture",
          "Traditionalfoodproducts": "Produits alimentaires traditionnels.",
          "Medicine456sdf": "Médicaments",
          "Expressdeliveryofurgentmedications": "Livraison express de médicaments urgents.",
          "Pleasecheckthelist": "*Veuillez vérifier la liste des produits autorisés par votre société de transport.",
          "Examplesofpurchases": "Exemples d'achats",
          "Koreanskincare": "Soins de la peau coréens",
          "AuthenticKoreanBeauty": "Produits authentiques de beauté et soins coréens.",
          "Clothes4545": "Vêtements",
          "Internationalfashion": "Mode et tendances internationales.",
          "Limitededitionsneakers": "Baskets en édition limitée.",
          "Exclusivemodelsandrarecollections.": "Modèles exclusifs et collections rares.",
          "Allproductsaresubjecttocurrentcustomsregulations": "* * Tous les produits sont soumis aux réglementations douanières en vigueur.",
          'Identityverified': 'Identité vérifiée',
          'Allusersareverifiedincluding': "Tous les utilisateurs sont vérifiés, y compris les expéditeurs, les acheteurs et les voyageurs, avec validation des billets pour garantir un service fiable et sécurisé.",
          'Securepayment3554': 'Paiement sécurisé',
          'Paymentsarehelduntildeliverytransparent': "Les paiements sont retenus jusqu'à la confirmation de la livraison, assurant une transaction sûre et transparente.",
          'Securitycode2541': 'Code de sécurité',
          'Two5445zdf41': 'Deux',
          '4digitcodes': 'codes à 4 chiffres',
          'secureeachstepuponhandover': "sécuriser chaque étape : lors de la remise et de la livraison, garantissant une traçabilité et une sécurité maximales.",
          'CoBagInsurance345': 'Assurance CoBag',
          'BenefitfromcomprehensivecoveragewithCoBag': "Bénéficiez d'une couverture complète avec CoBag",
          'insurance5sd54ff': "assurance",
          'protectingyourparcelsupto': ', protégeant vos colis jusqu’à',
          'prices€1000': '€1000',
          'incaseincidentpeacemindyourshipments': "en cas d'incident. Voyagez l'esprit tranquille, vos expéditions sont sécurisées.",
          "CoBagTravelshareconnect": "CoBag : Voyagez, partagez, connectez.",
          "Whatifyoursuitcaseisvaluable": "Et si votre valise avait plus de valeur que vous ne le pensiez ?",
          "Turnyourunusedluggagespace": "Transformez l'espace inutilisé de votre bagage en une opportunité rentable. Avec CoBag, chaque voyage devient une occasion",
          "Earnmoneywhilehelpingothers": "de gagner de l'argent tout en aidant les autres.",
          "heading1212121": "CoBag : Transformez l'espace supplémentaire en opportunités !",
          "paragraph1121212": "CoBag est une plateforme révolutionnaire qui connecte les voyageurs, les expéditeurs et les acheteurs pour maximiser l'utilisation de l'espace de bagages inutilisés. Que vous voyagiez léger, que vous ayez des excédents de bagages ou que vous ayez besoin de transporter quelque chose à l'international, CoBag vous couvre.",
          "heading2456": "Comment ça marche ?",
          "step1_title": "Pour les voyageurs vendant des kilos inutilisés :",
          "step1_description": "Vous avez des kilos en trop dans vos bagages ? Listez votre voyage sur CoBag et proposez votre espace de bagages inutilisé à ceux qui en ont besoin. Transportez des bagages excédentaires, des colis ou même des achats internationaux. Gagnez de l'argent facilement et en toute sécurité pendant vos voyages.",
          "step2_title": "Pour ceux qui ont des bagages excédentaires :",
          "step2_description": "Évitez les frais aériens coûteux en louant des kilos inutilisés auprès des voyageurs prenant déjà le même vol ou train. Remettez vos bagages excédentaires en toute sécurité et économisez de l'argent.",
          "step3_title": "Pour les acheteurs internationaux :",
          "step3_description": "Vous cherchez un produit introuvable dans votre pays ? Connectez-vous avec un voyageur dans la région qui peut l'acheter pour vous et le ramener. Payez en toute sécurité via la plateforme et recevez votre article dès le retour du voyageur.",
          "step4_title": "Pour les expéditeurs de colis :",
          "step4_description": "Vous devez envoyer un colis rapidement ? CoBag vous connecte avec un voyageur se rendant à votre destination souhaitée. Organisez la livraison, en personne ou via un casier sécurisé à l'aéroport.",
          "WhyChooseCoBag45": "Pourquoi choisir CoBag ?",
          "Secure456": "Les identités des utilisateurs, les voyages et les contenus des colis sont vérifiés. Les paiements sont retenus jusqu'à ce que la mission soit réalisée avec succès.",
          "EcoFriendly546": "CoBag utilise l'espace dans les vols et trains déjà en circulation, réduisant ainsi les émissions inutiles de CO2.",
          "Affordable456456": "Économisez sur les frais d'excédent de bagages coûteux et les frais d'expédition internationaux.",
          "Flexible4566": "Choisissez le service qui correspond à vos besoins—que vous vendiez des kilos, envoyiez des colis ou fassiez des achats à l'étranger.",
          "JoinTheCoBagMovement54645": "Rejoignez le mouvement CoBag dès aujourd'hui ! Que vous soyez un voyageur, un expéditeur ou un acheteur, CoBag vous aide à tirer le meilleur parti de chaque voyage. Transformez l'espace de bagages inutilisé en opportunités et découvrez une façon plus intelligente et plus écologique de voyager.",
          "SignUpNow456": "Inscrivez-vous maintenant",
          "logoitem101": "Co",
          "logoitem102": "B",
          "logoitem103": "ag Lorsque Votre",
          "Luggage542121": "Bagages",
          "TravelsforYouandforOthers": "Voyage pour vous... et pour les autres.",
          "CoBagwasborn455": "CoBag est né d'un moment d'inspiration lors d'un voyage qui a révélé le potentiel caché de l'espace inutilisé dans les bagages. Ce qui a commencé comme une simple frustration est devenu une manière révolutionnaire de connecter les gens à travers le monde.",
          "birthOfIdeaTitle2": "La naissance d'une idée",
          "birthOfIdeaDescription2": "Le fondateur de CoBag a eu l'idée de sa startup en voyage. En chemin, il avait des bagages pleins à craquer, entre souvenirs et cadeaux, et ne pouvait pas tout emporter. Mais au retour, ses valises étaient vides... et pourtant, il avait déjà payé pour tout cet espace inutilisé et gaspillé.",
          "revolutionaryTitle": "Révolutionnaire",
          "revolutionaryDescription": "C'est alors que l'idée lui est venue : pourquoi ne pas partager cet espace inutilisé avec d'autres personnes ? Une solution simple mais efficace pour utiliser intelligemment l'espace libre des bagages, réduisant ainsi le nombre d'avions et de camions sur les routes, et donc l'empreinte carbone. Une solution innovante, écologique et extrêmement rapide : en seulement quelques heures, le temps d'un vol direct, un colis traverse le monde pour être livré encore plus rapidement que l'express.",
          "notOnlyThatTitle": "Mais ce n'est pas tout",
          "notOnlyThatDescription": "Mais ce n'est pas tout : pendant son voyage, le fondateur a également remarqué un autre besoin. Tout le monde n'a pas de proches ou d'amis voyageant à l'international pour ramener des produits rares ou exclusifs. Avec CoBag, les voyageurs peuvent désormais acheter et ramener des produits du monde entier pour ceux qui en ont besoin.",
          "joinTheRevolutionTitle": "Rejoignez la révolution CoBag aujourd'hui et voyagez intelligemment avec vos bagages !",
          "commissionMessage21": "Profitez de 0 % de commission sur toutes vos missions avec",
          "monthlyFeeMessage": "Pour seulement 10 € par mois, sans engagement, optimisez vos gains et réduisez vos coûts à chaque transaction.",
          "Subscribenow1": "Abonnez-vous maintenant",
          "TheCoBagSkyAdvantages": "Les avantages de CoBag Sky",
          "PremiumExperience": "Une expérience premium pour optimiser vos missions",
          "ZeroCommissions": "0% de commissions",
          "ZeroCommissionFee": "Frais de commission de 0%. Une solution idéale pour maximiser vos gains",
          "InsurancePlusIncluded": "Assurance Plus incluse",
          "EnjoyCompleteFlexibility": "Profitez d'une flexibilité totale avec la possibilité d'annuler à tout moment. Restez maître de votre abonnement",
          "NoCommitment": "Sans engagement",
          "StayInControl": "Profitez d'une flexibilité totale avec la possibilité d'annuler à tout moment. Restez maître de votre abonnement",
          "OneSubscriptionUniqueBenefits": "Un abonnement, des avantages uniques",
          "PricePerMonth": "10€",
          "ZeroCommission": "0% de commission sur toutes les transactions",
          "NoCommitment2": "Sans engagement : liberté totale",
          "ImmediateSavings": "Économies immédiates pour les acheteurs et les vendeurs",
          "InsurancePlusIncluded": "Assurance Plus incluse jusqu'à 500€",
          "CoBagSkyBadge": "Badge CoBag Sky sur votre profil",
          "PricePerMonthSaved": " mois économisés par nos membres",
          "SavingsByMembers": "Les membres économisent en moyenne 30€ par mois avec CoBag Sky*",
          "AverageSavingsExplanation": "*Économies moyennes réalisées par mois, calculées sur la base de toutes les missions effectuées sur un mois, grâce aux frais de commission de 0€",
          "BecomeAMember": "Devenez membre pour seulement 10€ par mois",
          "BenefitsUsableAnywhere": "Vos avantages sont utilisables partout où CoBag Sky est présent",
          "OfferYourJourney": "Proposez votre voyage, rendez vos bagages rentables.",
          "ResellUnusedKilos": "Revendez vos kilos inutilisés et transformez vos voyages en opportunités lucratives.",
          "Plane": "Avion",
          "Train": "Train",


          "TransportMood": "Mode de transport",
          "Direct": "Direct",
          "WithCorrespondence": "Avec correspondance",
          "AddYourTicket": "(PNG, JPG ou PDF jusqu'à 10 Mo)",
          "FlightNumber": "Numéro de vol",
          "DepartureCity": "Ville de départ",
          "ArrivalCity": "Ville d'arrivée",
          "DepartureDate": "Date de départ",
          "ArrivalDate": "Date d'arrivée",
          "DepartureTime": "Heure de départ",
          "ArrivalTime": "Heure d'arrivée",
          "AvailableWeight": "Poids disponible",
          "HandLuggage": "Bagages à main",
          "CheckedBaggage": "Bagages enregistrés",
          "AvailableToBeACourier": "Disponible pour être un messager",
          "MaximumPurchaseAmountYouAreWillingToAdvance": "Montant maximum d'achat que vous êtes prêt à avancer.",
          "EnterTheAmount": "Entrez le montant",
          "ThisAmountWillBeVisibleToPotentialBuyers": "Ce montant sera visible pour les acheteurs potentiels.",
          "MessageOptional": "Message (facultatif)",
          "PublishRoute": "Publier l'itinéraire",






        }
      }


    },
    lng: 'fn', // if you're using a language detector, do not define the lng option
    fallbackLng: "fn",

    interpolation: {
      escapeValue: false // react already safes from xss => https://www.i18next.com/translation-function/interpolation#unescape
    }
  });




export default i18n;